[build-system]
requires = ["setuptools", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["asset_gen"]

[project]
name = "asset_gen"
version = "v0.1.7"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

dependencies = []
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "cpplint",
    "pre-commit",
    "pydocstyle",
    "black",
    "isort",
    "pytest",
    "pytest-mock",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-git-revision-date-localized-plugin",
]

[project.scripts]
drender-cli = "asset_gen.data.differentiable_render:entrypoint"
backproject-cli = "asset_gen.data.backproject_v2:entrypoint"
img3d-cli = "asset_gen.scripts.imageto3d:entrypoint"
text3d-cli = "asset_gen.scripts.textto3d:text_to_3d"

[tool.pydocstyle]
match = '(?!test_).*(?!_pb2)\.py'
match-dir = '^(?!(raw|projects|tools|k8s_submit|thirdparty)$)[\w.-]+$'
convention = "google"
add-ignore = 'D104,D107,D202,D105,D100,D102,D103,D101,E203'

[tool.pycodestyle]
max-line-length = 79
ignore = "E203"

[tool.black]
line-length = 79
exclude = "thirdparty"
skip-string-normalization = true

[tool.isort]
line_length = 79
profile = 'black'
no_lines_before = 'FIRSTPARTY'
known_first_party = ['asset_gen']
skip = "thirdparty/"