# agent_type: "ollama" | "qwen2.5-vl" | "gpt-4o"
agent_type: "ollama"

ollama:
  endpoint: http://localhost:11434/v1
  api_key: ollama
  api_version: null
  model_name: qwen3.5:cloud

gpt-4o:
  endpoint: https://xxx.openai.azure.com
  api_key: xxx
  api_version: 2025-xx-xx
  model_name: yfb-gpt-4o

qwen2.5-vl:
  endpoint: https://openrouter.ai/api/v1
  api_key: sk-or-v1-xxx
  api_version: null
  model_name: qwen/qwen2.5-vl-72b-instruct:free
